import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="th">
      <body className="min-h-screen bg-gray-50">
        <header className="border-b bg-white">
          <nav className="mx-auto max-w-6xl px-4 h-14 flex items-center gap-3">
            <Link href="/" className="font-semibold">Si-Wara POS</Link>
            <div className="ml-auto flex gap-2 text-sm">
              <Link href="/shift" className="px-3 py-1 rounded hover:bg-gray-100">รายรับ-รายจ่าย</Link>
              <Link href="/reports" className="px-3 py-1 rounded hover:bg-gray-100">รายงาน</Link>
              <Link href="/stock" className="px-3 py-1 rounded hover:bg-gray-100">stock</Link>
              <Link href="/recipes" className="px-3 py-1 rounded hover:bg-gray-100">สูตรเมนู</Link>
              <Link href="/pos" className="px-3 py-1 rounded hover:bg-gray-100">หน้าร้าน</Link>
              <Link href="/queue" className="px-3 py-1 rounded hover:bg-gray-100">คิวหน้าบาร์</Link>
              <Link href="/products" className="px-3 py-1 rounded hover:bg-gray-100 dark:hover:bg-neutral-800">เมนู</Link>
              <Link href="/orders" className="px-3 py-1 rounded hover:bg-gray-100 dark:hover:bg-neutral-800">ดูบิล</Link>



            </div>
          </nav>
        </header>
        <main className="mx-auto max-w-6xl px-4 py-6">{children}</main>
      </body>
    </html>
  );
}


